name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # GitHub 웹페이지에서 수동으로 빌드 버튼을 누를 수 있게 합니다.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Add Android Platform
      run: cordova platform add android

    - name: Build Android App (Debug APK)
      run: cordova build android --debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TheMore-HJ-APK
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

    - name: 생성된 APK 파일 저장하기
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        # 경로를 조금 더 상위 폴더로 잡아서, 그 안에 있는 모든 apk를 다 가져오게 합니다.
        path: platforms/android/app/build/outputs/apk/**/*.apk
